#ifndef TEXTUREATLAS_H
#define TEXTUREATLAS_H

#include <fstream>
#include <vector>
#include <sparsehash/dense_hash_map>
#include <boost/dynamic_bitset.hpp>
#include <cstring>
#include <zlib.h>
#include <gl.h>
#include <GL/Rect.hpp>
#include "Texture.h"
#include "Sprite.h"

/* Class for loading .bin files and associated .dds.gz files, generated by recrunch */
class TextureAtlas{
public:
	TextureAtlas();
	bool loadFromFile(const std::string& file_path);
	const Texture findSubTexture(const std::string& name);
	std::vector<std::string> getSubTextureNames();
	bool PixelPerfectTest(const Sprite& Object1, const Sprite& Object2);
	~TextureAtlas(){
		if (m_texture_handles != nullptr){
			glDeleteTextures(m_num_textures,m_texture_handles);
			delete[] m_texture_handles;
		}
	}
	GLuint* m_texture_handles = nullptr;
	int m_num_textures;

private:
	struct Atlas
	{
		Atlas(){
			m_texture_table.set_empty_key("");
		}
		google::dense_hash_map<std::string, Texture> m_texture_table;
		GLuint* m_texture = nullptr;
		GLuint format;
		uint16_t width=0, height=0;
	};
	struct Bitmask{
		uint16_t width=0;
		uint16_t height=0;
		boost::dynamic_bitset<> mask;
	};
	bool loadDDSgz(const std::string& path, Atlas& atlas);
	bool loadBINgz(const std::string& path, const Atlas& atlas);
	std::vector<Atlas> m_atlas_list;
	google::dense_hash_map<GLuint, Bitmask> Bitmasks;
};

#endif
