#ifndef TEXTUREATLAS_H
#define TEXTUREATLAS_H
#include <parallel_hashmap/phmap.h>
#include <gl.h>
#include <vector>
#include "Rect.hpp"
#include "Bitmask.hpp"
#include "Texture.hpp"

using phmap::parallel_flat_hash_map;
/* Class for loading .bin.gz files and associated .dds.gz files, generated by recrunch */
class TextureAtlas{
public:
	explicit TextureAtlas(const std::string& file_path);
	const Texture findSubTexture(const std::string& name);
	const Bitmask& getBitmask(const Texture* tex);
	std::vector<std::string> getSubTextureNames();
	~TextureAtlas(){
		glDeleteTextures(m_num_textures,m_texture_handles.data());
	}
	std::vector<GLuint> m_texture_handles;
	int m_num_textures;

private:
	struct Atlas
	{
		Atlas(){
		}
		parallel_flat_hash_map<std::string, Texture> m_texture_table;
		GLuint m_texture = 0;
		GLuint format = 0;
		uint16_t width=0, height=0;
	};
	bool loadDDSgz(const std::string& path, Atlas& atlas);
	bool loadBINgz(const std::string& path, const Atlas& atlas);
	std::vector<Atlas> m_atlas_list;
	parallel_flat_hash_map<GLuint, Bitmask> Bitmasks;
};

#endif
